name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_USER }}
        password: ${{ secrets.GH_TOKEN }}
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
        #workingDirectory: another/path/where/a/git/repo/is/checked/out # Optional alternative working directory
    - name: 'Get next minor version'
      id: semvers
      uses: "WyriHaximus/github-action-next-release-version@v1"
      with:
        version: ${{ steps.previoustag.outputs.tag }}
    - name: Create release
      id: create_release_id
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: ${{ steps.semvers.outputs.version }}
        release_name: Release ${{ steps.semvers.outputs.version }}
        
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/${{ secrets.GH_USER }}/tempapp:${{ steps.semvers.outputs.patch }}
        docker push ghcr.io/cyrenity/tempapp:${{ steps.semvers.outputs.patch }}

