name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_USER }}
        password: ${{ secrets.GH_TOKEN }}
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tempapp:$(date +%s)
