name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main 
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_USER }}
        password: ${{ secrets.GH_TOKEN }}
   
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/${{ secrets.GH_USER }}/tempapp:latest --tag ghcr.io/${{ secrets.GH_USER }}/tempapp:${GITHUB_SHA::7} 
        docker push ghcr.io/cyrenity/tempapp:latest

